name: Go

on:
  push:
    branches: golang
#   pull_request:
#     branches: [ $default-branch ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Build
      run: go build -v server

    - name: Test
      run: go test -v server